default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>

development:
  <<: *default
  host: <%= ENV['LOCAL_DATABASE_HOST'] %>
  username: <%= ENV['LOCAL_DATABASE_USERNAME'] %>
  password: <%= ENV['LOCAL_DATABASE_PASSWORD'] %>
  database: <%= ENV['LOCAL_DATABASE_NAME'] %>

production:
  <<: *default
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
